---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - student.kubecombo.com
  resources:
  - students
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - student.kubecombo.com
  resources:
  - students/finalizers
  verbs:
  - update
- apiGroups:
  - student.kubecombo.com
  resources:
  - students/status
  verbs:
  - get
  - patch
  - update
