# permissions for end users to view students.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/managed-by: kustomize
  name: student-viewer-role
rules:
- apiGroups:
  - student.kubecombo.com
  resources:
  - students
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - student.kubecombo.com
  resources:
  - students/status
  verbs:
  - get
